
general:
  cpiApiServiceKeyCredentialsId: "roverazurewesteu20-credentials"
  integrationFlowId: "ReceiveAdvice"
stages:
  uploadStage:
    enabled: true
steps:
  integrationArtifactUpload:
    packageId: "SunnysPackage"
    integrationFlowName: "ReceiveAdvice"
    filePath: "ReceiveAdvice.zip"
