
general:
  cpiApiServiceKeyCredentialsId: "roverazurewesteu20-credentials"
  integrationFlowId: "ReceiveAdvice"
stages:
  uploadStage:
    enabled: true
  deployStage:
    enabled: false
  integrationTestStage:
    enabled: false
steps:
  integrationArtifactUpload:
    packageId: "SunnysPackage"
    integrationFlowName: "ReceiveAdvice"
    filePath: "ReceiveAdvice.zip"
    verbose:true
