steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: roverazurewesteu20-credentials
    integrationFlowId: ReceiveAdvice
    integrationFlowName: ReceiveAdvice
    packageId: SunnysPackage
    filePath: ReceiveAdvice.zip
